# Base image
FROM php:8.1-cli-alpine

# Install system dependencies
RUN apk update && apk add --no-cache \
    git \
    npm \
    vim \
    zip \
	bash

# Install Node.js
RUN apk add --update nodejs npm

RUN npm i -g yarn

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

WORKDIR /app
