FROM php:8.1-fpm-alpine

ARG user
ARG uid

RUN apk update && apk upgrade --available && sync
RUN apk add --update linux-headers vim
RUN set -ex \
	&& apk --no-cache add \
	postgresql-dev oniguruma-dev libpng-dev
RUN docker-php-ext-install pdo_pgsql exif pcntl bcmath gd opcache
RUN apk add --no-cache $PHPIZE_DEPS

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN adduser -u "$uid" --disabled-password "$user"
RUN addgroup $user www-data
RUN addgroup $user root
RUN addgroup $user wheel

RUN apk add sudo

RUN echo "$user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$user && chmod 0440 /etc/sudoers.d/$user

RUN mkdir -p /home/$user/.composer
RUN chown -R $user:$user /home/$user
USER $user
WORKDIR /var/www

USER $user
