version: '3'

services:
  cewb-app:
    build:
      args:
        user: cewb
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    image: cewb-dev
    restart: unless-stopped
    container_name: cewb-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cewb-network

  cewb-db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: cewb-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cewb-db-data:/var/lib/postgresql/data
    networks:
      - cewb-network

  cewb-redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: cewb-redis
    networks:
      - cewb-network

  cewb-nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    container_name: cewb-nginx
    ports:
      - 9898:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - cewb-network

networks:
  cewb-network:
    driver: bridge

volumes:
  cewb-db-data:
