# Base image
FROM php:8.1-fpm-alpine

# Install dependencies
USER root

# Install PHP 8.1 and necessary extensions
RUN apk update && apk upgrade  && \
    apk add --no-cache bash git unzip zip curl libpng-dev libzip-dev postgresql-dev && \
    docker-php-ext-install pdo pdo_pgsql opcache bcmath && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS && \
    pecl install redis && \
    docker-php-ext-enable redis && \
    apk del .build-deps

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Node.js 18 and Yarn
RUN apk add --no-cache nodejs npm yarn

WORKDIR /var/www
COPY composer.json ./
