version: "3"

services:
    cewb-app:
        extra_hosts:
          - host.docker.internal:host-gateway
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: cewb-dev
        container_name: cewb-app
        restart: unless-stopped
        networks:
            - cewbs-network
        volumes:
            - ./:/var/www/html
    cewb-redis:
      image: redis:alpine
      container_name: cewb-redis
      restart: unless-stopped
      networks:
        - cewbs-network
      ports:
        - 65379:6379

    cewb-nginx:
        extra_hosts:
          - host.docker.internal:host-gateway
        image: nginx:latest
        container_name: cewb-nginx
        restart: unless-stopped
        networks:
            - cewbs-network
        ports:
            - 9898:80
        volumes:
            - ./:/var/www/html
            - ./docker_config/nginx_dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - cewb-app

networks:
    cewbs-network:
        driver: bridge
