version: '3'
services:
<<<<<<< HEAD
  cewb-app:
    build:
      args:
        user: cewb
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    image: cewb-dev
    restart: unless-stopped
    container_name: cewb-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cewb-network

  cewb-db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: cewb-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cewb-db-data:/var/lib/postgresql/data
    networks:
      - cewb-network

  cewb-redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: cewb-redis
    networks:
      - cewb-network

  cewb-nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: cewb-nginx
    ports:
      - 9898:80
    volumes:
      - ./:/var/www
      - ./docker_config/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cewb-network

=======
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - pgsql
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
>>>>>>> parent of 91983d6 (ci: github actions)
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-pgsql:
        driver: local
