# Base image
FROM php:8.1-fpm-alpine

# Install PHP 8.1 and necessary extensions
RUN apk update && apk upgrade  && \
    apk add --no-cache bash git unzip zip curl libpng-dev libzip-dev postgresql-dev && \
    docker-php-ext-install pdo pdo_pgsql opcache bcmath && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS && \
    pecl install redis && \
    docker-php-ext-enable redis && \
    apk del .build-deps

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apk --no-cache add shadow && usermod -aG www-data root
# Install Node.js 18 and Yarn
RUN apk add --no-cache nodejs npm yarn

# Set ownership and permissions
WORKDIR /var/www
COPY --chown=1000:www-data . /var/www
# Set up permissions
RUN chown -R 1000:www-data /var/www