name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts --no-suggest

      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: yarn build

      - name: Generate environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: your-dockerhub-username/your-image-name:latest
